# Generated by Django 5.2.6 on 2026-02-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JadRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=250, verbose_name='Source ID')),
                ('target_id', models.CharField(max_length=250, verbose_name='Target ID')),
                ('distance', models.FloatField(verbose_name='selected max distance')),
            ],
            options={
                'verbose_name': 'Jad relation',
                'verbose_name_plural': 'Jad relations',
                'ordering': ['-id'],
                'unique_together': {('source_id', 'target_id', 'distance')},
            },
        ),
    ]
